updated-deploy

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -88,10 +88,9 @@ jobs:
 
       - name: Stop and remove container if running
         run: |
-          if docker ps -q --filter "name=cnncls" | grep -q .; then
-            docker stop cnncls
-            docker rm -fv cnncls
-          fi
+          docker stop cnncls 2>/dev/null || echo "Container not running"
+          docker rm -fv cnncls 2>/dev/null || echo "Container not found"
+
        
       - name: Run Docker Image to serve users
         run: |
